# from django.contrib.auth import get_user_model
# from django.core.exceptions import ValidationError
#
#
# def validate_username(username):
#     if get_user_model().objects.filter(username=username).exists():
#         raise ValidationError("Username already exists")
